### PR TITLE
Initial local file access

### PR DESCRIPTION
**Pull request by pentacular**

### CODE REVIEW

**Review by BarbourSmith — APPROVED** [review]
Awesome! From a user perspective does supporting local files mean that users can edit files on their computer directly through the web interface?

**Comment by pentacular** [comment]
> Awesome! From a user perspective does supporting local files mean that users can edit files on their computer directly through the web interface?

Not yet. :)

This just allows you to read http://a/b/c off e.g., ~/c

But, yes, it should be extended to allow direct editing of source and automatic output of downloads, etc.

**Comment by hrgdavor** [comment]
what is used to run the standalone app ?

**Comment by pentacular** [comment]
> what is used to run the standalone app ?

See https://jsxcad.js.org/nb/index.html for an example.

**Pull request merged**
