### PR TITLE
Rebase square, circle, triangle on polygon. Support apothem.

### PR DESCRIPTION
**Pull request by pentacular**

### CODE REVIEW

**Comment by BarbourSmith** [comment]
Nice! Using polygon as a base makes a lot of sense

**Comment by pentacular** [comment]
Thinking of doing likewise with prism for solids.

**Comment by BarbourSmith** [comment]
That makes sense to me. Can all of the solids be covered by prism?

**Comment by pentacular** [comment]
No :)

Cube and cylinder can be.

Tetrahedron, sphere, etc, not so much.

**Pull request merged**
