### PR TITLE
Sync up with JSxCAD Master

### PR DESCRIPTION
**Pull request by BarbourSmith**
I know this is about to be obsolete, but I figure we might as well sync up right before that anyway for good record keeping

### CODE REVIEW

**Comment by BarbourSmith** [comment]
Oops, gotta lint

**Comment by BarbourSmith** [comment]
I'm seeing the CI fail with:

image

But I am unsure what to do to make it happier

**Comment by pentacular** [comment]
It's due to:

Missing dependencies
* @jsxcad/cache: ./maslowWorker.js

**Comment by BarbourSmith** [comment]
Thanks!

**Pull request merged**
