### PR TITLE
Remove puppeteer and switch to headless rendering to png

### PR DESCRIPTION
**Pull request by pentacular**

### CODE REVIEW

**Review by BarbourSmith — APPROVED** [review]
Other than a tiny bit of rasterization these all look fantastic!

**Comment by BarbourSmith** [comment]
Is the rasterization deterministic so it won't make the test fail when comparing the output? It should be, right?

**Comment by pentacular** [comment]
> Other than a tiny bit of rasterization these all look fantastic!

Yeah, I can't quite figure it out, except that perhaps it's related to devicePixelRatio causing the browser to oversample.

**Comment by pentacular** [comment]
> Is the rasterization deterministic so it won't make the test fail when comparing the output? It should be, right?

I hope so, but mostly I wanted to (a) remove the dependency on pupeteer, and (b) support thumbnail generation.

So now we should be able to say shape.png('foo') and be able to get a png of that view of shape.

**Pull request merged**
