### PR TITLE
Update the maslowWorker.js file to include gcode generation 

### PR DESCRIPTION
**Pull request by BarbourSmith**
This is almost certainly going to fail lint, but I think the tests run faster on travis than on my computer so I'm going to read the error messages there :D

### CODE REVIEW

**Comment by BarbourSmith** [comment]
Boy howdy that's a lot of errors 😬 

Is there a way to run the lintfix command just in the /ui/v1 folder?

**Comment by BarbourSmith** [comment]
I got lint to be happy, but now I'm not sure where I'm failing 😢

**Comment by pentacular** [comment]
Ah, it's an unused dependency -- you can see by scrolling through the travis details.

But that's ok -- I'll sort it out later -- thanks. :)

**Comment by BarbourSmith** [comment]
Thanks!

I know exactly what it was. I removed one of the imports, but forgot to remove it from the dependencies file.

How did you find it in the log? I found the lint issues by searching the log for "Error", but I couldn't find that last one

**Comment by pentacular** [comment]
Ah. I just scroll for the purple bits. :)

**Pull request merged**
