### PR TITLE
Improved Arrangement to Polygon translation.

### PR DESCRIPTION
**Pull request by pentacular**

### CODE REVIEW

**Review by BarbourSmith — APPROVED** [review]
Ive got a bit of a cold so I'm not at my sharpest, but this looks good to me as long as these tests look right:

image

image

It seems to be doing something in particular to 2D cutting interactions

**Comment by pentacular** [comment]
> Ive got a bit of a cold so I'm not at my sharpest, but this looks good to me as long as these tests look right:
> 
> image image
> It seems to be doing something in particular to 2D cutting interactions

Yes, I need to fix that. :)

We have NonZero and EvenOdd winding rules for arrangement-to-polygon conversion, which got a bit confused.

I'll finish separating those out properly and fix that reversion before merging. :)

Thanks for confirming that.

**Comment by BarbourSmith** [comment]
I see now that you didn't request a review yet. Sorry if I was telling you things you already knew :p

**Comment by pentacular** [comment]
> I see now that you didn't request a review yet. Sorry if I was telling you things you already knew :p

Oh, not at all -- you confirmed the issue, and didn't see any other problems -- which is great. :)

**Comment by pentacular** [comment]
> > I see now that you didn't request a review yet. Sorry if I was telling you things you already knew :p
> 
> Oh, not at all -- you confirmed the issue, and didn't see any other problems -- which is great. :)

I think it's fixed now. :)

**Pull request merged**
